ARG stack
FROM packs/cf

# runs packs to build a droplet (in a volume)

ARG buildpacks

WORKDIR /workspace

RUN mkdir -p /packs

COPY builder /packs/
COPY runner /packs/

ENTRYPOINT [ \
  "/packs/runner" \
]
