// Code generated by counterfeiter. DO NOT EDIT.
package eirinifakes

import (
	"sync"

	"code.cloudfoundry.org/bbs/models"
	"code.cloudfoundry.org/eirini"
	"code.cloudfoundry.org/runtimeschema/cc_messages"
)

type FakeStager struct {
	DesireTaskStub        func(string, cc_messages.StagingRequestFromCC) error
	desireTaskMutex       sync.RWMutex
	desireTaskArgsForCall []struct {
		arg1 string
		arg2 cc_messages.StagingRequestFromCC
	}
	desireTaskReturns struct {
		result1 error
	}
	desireTaskReturnsOnCall map[int]struct {
		result1 error
	}
	BuildStagingResponseStub        func(*models.TaskCallbackResponse) (cc_messages.StagingResponseForCC, error)
	buildStagingResponseMutex       sync.RWMutex
	buildStagingResponseArgsForCall []struct {
		arg1 *models.TaskCallbackResponse
	}
	buildStagingResponseReturns struct {
		result1 cc_messages.StagingResponseForCC
		result2 error
	}
	buildStagingResponseReturnsOnCall map[int]struct {
		result1 cc_messages.StagingResponseForCC
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStager) DesireTask(arg1 string, arg2 cc_messages.StagingRequestFromCC) error {
	fake.desireTaskMutex.Lock()
	ret, specificReturn := fake.desireTaskReturnsOnCall[len(fake.desireTaskArgsForCall)]
	fake.desireTaskArgsForCall = append(fake.desireTaskArgsForCall, struct {
		arg1 string
		arg2 cc_messages.StagingRequestFromCC
	}{arg1, arg2})
	fake.recordInvocation("DesireTask", []interface{}{arg1, arg2})
	fake.desireTaskMutex.Unlock()
	if fake.DesireTaskStub != nil {
		return fake.DesireTaskStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.desireTaskReturns.result1
}

func (fake *FakeStager) DesireTaskCallCount() int {
	fake.desireTaskMutex.RLock()
	defer fake.desireTaskMutex.RUnlock()
	return len(fake.desireTaskArgsForCall)
}

func (fake *FakeStager) DesireTaskArgsForCall(i int) (string, cc_messages.StagingRequestFromCC) {
	fake.desireTaskMutex.RLock()
	defer fake.desireTaskMutex.RUnlock()
	return fake.desireTaskArgsForCall[i].arg1, fake.desireTaskArgsForCall[i].arg2
}

func (fake *FakeStager) DesireTaskReturns(result1 error) {
	fake.DesireTaskStub = nil
	fake.desireTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStager) DesireTaskReturnsOnCall(i int, result1 error) {
	fake.DesireTaskStub = nil
	if fake.desireTaskReturnsOnCall == nil {
		fake.desireTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.desireTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStager) BuildStagingResponse(arg1 *models.TaskCallbackResponse) (cc_messages.StagingResponseForCC, error) {
	fake.buildStagingResponseMutex.Lock()
	ret, specificReturn := fake.buildStagingResponseReturnsOnCall[len(fake.buildStagingResponseArgsForCall)]
	fake.buildStagingResponseArgsForCall = append(fake.buildStagingResponseArgsForCall, struct {
		arg1 *models.TaskCallbackResponse
	}{arg1})
	fake.recordInvocation("BuildStagingResponse", []interface{}{arg1})
	fake.buildStagingResponseMutex.Unlock()
	if fake.BuildStagingResponseStub != nil {
		return fake.BuildStagingResponseStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.buildStagingResponseReturns.result1, fake.buildStagingResponseReturns.result2
}

func (fake *FakeStager) BuildStagingResponseCallCount() int {
	fake.buildStagingResponseMutex.RLock()
	defer fake.buildStagingResponseMutex.RUnlock()
	return len(fake.buildStagingResponseArgsForCall)
}

func (fake *FakeStager) BuildStagingResponseArgsForCall(i int) *models.TaskCallbackResponse {
	fake.buildStagingResponseMutex.RLock()
	defer fake.buildStagingResponseMutex.RUnlock()
	return fake.buildStagingResponseArgsForCall[i].arg1
}

func (fake *FakeStager) BuildStagingResponseReturns(result1 cc_messages.StagingResponseForCC, result2 error) {
	fake.BuildStagingResponseStub = nil
	fake.buildStagingResponseReturns = struct {
		result1 cc_messages.StagingResponseForCC
		result2 error
	}{result1, result2}
}

func (fake *FakeStager) BuildStagingResponseReturnsOnCall(i int, result1 cc_messages.StagingResponseForCC, result2 error) {
	fake.BuildStagingResponseStub = nil
	if fake.buildStagingResponseReturnsOnCall == nil {
		fake.buildStagingResponseReturnsOnCall = make(map[int]struct {
			result1 cc_messages.StagingResponseForCC
			result2 error
		})
	}
	fake.buildStagingResponseReturnsOnCall[i] = struct {
		result1 cc_messages.StagingResponseForCC
		result2 error
	}{result1, result2}
}

func (fake *FakeStager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.desireTaskMutex.RLock()
	defer fake.desireTaskMutex.RUnlock()
	fake.buildStagingResponseMutex.RLock()
	defer fake.buildStagingResponseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ eirini.Stager = new(FakeStager)
